site_name: ele
docs_dir: docs/
nav:
    - Home: index.md
    - Install: install.md
    - Data sources: sources.md
theme:
    name: material
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
